apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-storage-pvc
spec:
  accessModes:
    - ReadWriteMany  # Allow multiple pods to read and write
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
