apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repo-handler
  template:
    metadata:
      labels:
        app: repo-handler
    spec:
      containers:
        - name: repo-handler
          image: python:3.12-slim
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt-get update && \
              apt-get install -y git librdkafka-dev gcc python3-dev && \
              mkdir -p /mnt/app && \
              tar -xzf /app/app-code.tar.gz -C /mnt/app && \
              cd /mnt/app && \
              pip install --no-cache-dir -r /mnt/app/requirements.txt && \
              uvicorn main:app --host 0.0.0.0 --port 8000
          volumeMounts:
            - mountPath: "/mnt/app"
              name: app-storage
            - mountPath: "/app/app-code.tar.gz"
              subPath: app-code.tar.gz
              name: app-code
            - mountPath: "/data/repos"
              name: repo-storage
          ports:
            - containerPort: 8000
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.default.svc.cluster.local:9092"
            - name: PYTHONUNBUFFERED
              value: "1"
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-code-pvc
        - name: app-code
          configMap:
            name: app-code-configmap
        - name: repo-storage
          persistentVolumeClaim:
            claimName: repo-storage-pvc
