apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

configMapGenerator:
- name: app-code-configmap
  files:
  - main.py
  - facade.py
  - requirements.txt
  - templates/upload.html